-- Create discussions/posts table
create table if not exists discussions (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  content text not null,
  media_id text, -- Optional: link to a movie/tv show
  media_type text check (media_type in ('movie', 'tv')),
  media_title text, -- Cached title for display
  media_poster text, -- Cached poster for display
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create comments table (replies to discussions)
create table if not exists comments (
  id bigint generated by default as identity primary key,
  discussion_id bigint references discussions(id) on delete cascade not null,
  user_id uuid references profiles(id) on delete cascade not null,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table discussions enable row level security;
alter table comments enable row level security;

-- Policies for discussions
create policy "Discussions are viewable by everyone." on discussions
  for select using (true);

create policy "Users can create discussions." on discussions
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own discussions." on discussions
  for update using (auth.uid() = user_id);

create policy "Users can delete their own discussions." on discussions
  for delete using (auth.uid() = user_id);

-- Policies for comments
create policy "Comments are viewable by everyone." on comments
  for select using (true);

create policy "Users can create comments." on comments
  for insert with check (auth.uid() = user_id);

create policy "Users can update their own comments." on comments
  for update using (auth.uid() = user_id);

create policy "Users can delete their own comments." on comments
  for delete using (auth.uid() = user_id);
