-- Create Favorites Table
create table if not exists favorites (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  media_id text not null,
  media_type text not null check (media_type in ('movie', 'tv')),
  title text,
  poster_path text,
  vote_average numeric,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  unique(user_id, media_id, media_type)
);

alter table favorites enable row level security;

create policy "Users can view their own favorites." on favorites
  for select using (auth.uid() = user_id);

create policy "Users can insert into their own favorites." on favorites
  for insert with check (auth.uid() = user_id);

create policy "Users can delete from their own favorites." on favorites
  for delete using (auth.uid() = user_id);
