-- Create reviews table
create table if not exists reviews (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  media_id text not null,
  media_type text check (media_type in ('movie', 'tv')),
  media_title text,
  media_poster text,
  rating integer check (rating >= 1 and rating <= 10),
  content text not null,
  season_number integer, -- For TV show episode reviews
  episode_number integer, -- For TV show episode reviews
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Separate replies table (polymorphic-ish or specific)
-- Let's use specific tables for simplicity and performance in Supabase
create table if not exists discussion_replies (
  id bigint generated by default as identity primary key,
  discussion_id bigint references discussions(id) on delete cascade not null,
  user_id uuid references profiles(id) on delete cascade not null,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists review_replies (
  id bigint generated by default as identity primary key,
  review_id bigint references reviews(id) on delete cascade not null,
  user_id uuid references profiles(id) on delete cascade not null,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Unified reactions table for likes/dislikes
create table if not exists reactions (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  target_id bigint not null,
  target_type text not null check (target_type in ('discussion', 'review', 'comment', 'discussion_reply', 'review_reply')),
  type text not null check (type in ('like', 'dislike')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, target_id, target_type)
);

-- Enable RLS
alter table reviews enable row level security;
alter table discussion_replies enable row level security;
alter table review_replies enable row level security;
alter table reactions enable row level security;

-- Policies for reviews
create policy "Reviews are viewable by everyone." on reviews for select using (true);
create policy "Users can create reviews." on reviews for insert with check (auth.uid() = user_id);
create policy "Users can update their own reviews." on reviews for update using (auth.uid() = user_id);
create policy "Users can delete their own reviews." on reviews for delete using (auth.uid() = user_id);

-- Policies for discussion_replies
create policy "Discussion replies are viewable by everyone." on discussion_replies for select using (true);
create policy "Users can create discussion replies." on discussion_replies for insert with check (auth.uid() = user_id);
create policy "Users can delete their own discussion replies." on discussion_replies for delete using (auth.uid() = user_id);

-- Policies for review_replies
create policy "Review replies are viewable by everyone." on review_replies for select using (true);
create policy "Users can create review replies." on review_replies for insert with check (auth.uid() = user_id);
create policy "Users can delete their own review replies." on review_replies for delete using (auth.uid() = user_id);

-- Policies for reactions
create policy "Reactions are viewable by everyone." on reactions for select using (true);
create policy "Users can create reactions." on reactions for insert with check (auth.uid() = user_id);
create policy "Users can update their own reactions." on reactions for update using (auth.uid() = user_id);
create policy "Users can delete their own reactions." on reactions for delete using (auth.uid() = user_id);

-- Indexes for performance
create index if not exists reviews_media_id_idx on reviews(media_id);
create index if not exists reactions_target_idx on reactions(target_id, target_type);
create index if not exists discussion_replies_discussion_id_idx on discussion_replies(discussion_id);
create index if not exists review_replies_review_id_idx on review_replies(review_id);
