-- Create Watch List Table
create table if not exists watch_list (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  media_id text not null,
  media_type text not null check (media_type in ('movie', 'tv')),
  title text,
  poster_path text,
  vote_average numeric,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  unique(user_id, media_id, media_type)
);

alter table watch_list enable row level security;

create policy "Users can view their own watch list." on watch_list
  for select using (auth.uid() = user_id);

create policy "Users can insert into their own watch list." on watch_list
  for insert with check (auth.uid() = user_id);

create policy "Users can delete from their own watch list." on watch_list
  for delete using (auth.uid() = user_id);

-- Create Watch History Table
create table if not exists watch_history (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  media_id text not null,
  media_type text not null check (media_type in ('movie', 'tv')),
  season_number int,
  episode_number int,
  progress int default 0, -- in seconds
  duration int default 0, -- in seconds
  last_watched_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  unique(user_id, media_id, media_type)
);

alter table watch_history enable row level security;

create policy "Users can view their own watch history." on watch_history
  for select using (auth.uid() = user_id);

create policy "Users can insert/update their own watch history." on watch_history
  for all using (auth.uid() = user_id);
